@api_base_url = http://localhost:3333
@access_token = {{authenticate.response.body.access_token}}

###
# @name create_account
POST {{api_base_url}}/accounts
Content-Type: application/json

{
	"name": "Rodrigo Orlandini",
	"email": "rodrigosorlandini@hotmail.com",
	"password": "12345678"
}

###
# @name authenticate
POST {{api_base_url}}/sessions
Content-Type: application/json

{
	"email": "rodrigosorlandini@hotmail.com",
	"password": "12345678"
}

###
# @name create_question
POST {{api_base_url}}/questions
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
	"title": "New question",
	"content": "Question content"
}

###
# @name fetch_recent_questions
GET {{api_base_url}}/questions?page=2
Content-Type: application/json
Authorization: Bearer {{access_token}}