version: "3.8"

services:
  postgres:
    container_name: ignite-node-nest-postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest
      PG_DATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

  cache:
    container_name: ignite-node-nest-cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data